### ISSUE TITLE
Pesan error system di modul login

### ISSUE THREAD

**Issue by apandi02** [zaunaf/xond#119]
Call to a member function getUsername() on a non-object

Terjadi jika kita memasukan username yang tidak ada di database

**Comment by apandi02** [comment]
mungkin solusinya

perbaikan di file
D:\Projects\localhost\simpak\vendor\xond\xond\src\Xond\Auth\UserProvider.php
on line 70
menjadi

```
        if($user){
            return new User($user->getUsername(), $user->getPassword(), array('ROLE_USER'), true, true, true, true);
        }else{
            return new User('username', 'password', array('ROLE_USER'), true, true, true, true);
        }
```

**Comment by zaunaf** [comment]
Duplicated with #120
