### ISSUE TITLE
Error on FrontEndGen

### ISSUE THREAD

**Issue by clasense4** [zaunaf/xond#124]
When I do FrontEndGen it produce error when all error turned on.

```
Notice: Undefined property: Xond\Gen\FrontEndGen::$outStr in D:\Projects\localhost\my_app\vendor\xond\xond\src\Xond\Gen\FrontEndGen.php line 459
```

My solution is add this piece of code, at `Gen\BaseGen.php` at `line 51`

```php
public $outStr;
```

Thanks

**Comment by zaunaf** [comment]
Ok thanks, will be fixed in the next commit.
